version: '2.2'
services:
  app:
    build:
      context: ../dockerfiles/web
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ../../../src:/opt/myapp/src
    init: true
    command:
      npm run start --prefix /opt/myapp/src/node
    logging:
      driver: "journald"
