version: '2.2'
services:
  web:
    build:
      context: ../dockerfiles/web
      dockerfile: "Dockerfile"
    environment:
      - NODE_ENV=development
    ports:
      - 3333:3000
    volumes:
      - ../../../src:/opt/myapp/src
    init: true
    command:
      tail -f /dev/null
